### PR TITLE
Use a different way to capture Y position when range reports incorrect p...

### LINKED ISSUE #525: Tapping on images on a post, makes editor scroll to the beggining of post
This happen on images that are still uploading, failed upload or are already part of the post.

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fix #525

Uses an updated from [ZSSRichTextEditor](https://github.com/nnhubbard/ZSSRichTextEditor/blob/master/ZSSRichTextEditor/ZSSRichTextEditor.js#L138)  to find the correct position of the caret.

/cc @diegoreymendez

### CODE REVIEW

**Comment by diegoreymendez** [comment]
@SergioEstevao - There's some code that's not really important to keep with these changes.  For instance the comments can be removed and the variable `needsToWorkAroundNewlineBug` doesn't make that much sense anymore.

I'd consider the following or something similar:

```javascript
ZSSEditor.getYCaretInfo = function() {
    var y = 0, height = 0;
    var sel = window.getSelection();
    if (sel.rangeCount) {
        
    var range = sel.getRangeAt(0);
        if (range.getClientRects) {
            var rects = range.getClientRects();
            
            if (rects.length > 0) {
                height = rects[0].height;
            } else {
                var fontSize = $(closerParentNode).css('font-size');
                var lineHeight = Math.floor(parseInt(fontSize.replace('px','')) * 1.5);
                
                height = lineHeight;
            }
        }
    }
    
    this.caretInfo.y = this.getCaretYPosition();
    this.caretInfo.height = height;
    
    return this.caretInfo;
};
```

File: Assets/ZSSRichTextEditor.js [hunk 1]
```diff
@@ -273,49 +273,66 @@ ZSSEditor.getJoinedCaretArguments = function() {
...
+    span.parentNode.removeChild(span);
+    return topPosition;
+}
+
+ZSSEditor.getYCaretInfo = function() {
+    var y = 0;
+    var height = 0;
+    var selection = window.getSelection();
+    
+    if (! selection.rangeCount) { // if no selection available just return 0
```
Comment (diegoreymendez) [inline Assets/ZSSRichTextEditor.js]: Remove space.

File: Assets/ZSSRichTextEditor.js [hunk 2]
```diff
@@ -273,49 +273,66 @@ ZSSEditor.getJoinedCaretArguments = function() {
...
+        this.caretInfo.y = y;
+        this.caretInfo.height = height;
+        return this.caretInfo;
+    }
+    
+    var range = selection.getRangeAt(0);
+    var needsToWorkAroundNewlineBug = (range.startOffset == 0 || range.getClientRects().length == 0);
```
Comment (diegoreymendez) [inline Assets/ZSSRichTextEditor.js]: We can remove this variable completely, since `range.startOffset == 0` was being used to detect problems with the `y` position calculation.

The only condition we need to check is `range.getClientRects().length == 0`, but we're already doing it far below... search my comment below for more info.

File: Assets/ZSSRichTextEditor.js [hunk 3]
```diff
@@ -273,49 +273,66 @@ ZSSEditor.getJoinedCaretArguments = function() {
...
+    
+    // PROBLEM: iOS seems to have problems getting the offset for some empty nodes and return
+    // 0 (zero) as the selection range top offset.
+    //
+    // WORKAROUND: To fix this problem we just get the node's offset instead.
+    //
+    if (needsToWorkAroundNewlineBug) {
+        var closerParentNode = ZSSEditor.closerParentNode();
```
Comment (diegoreymendez) [inline Assets/ZSSRichTextEditor.js]: The code written here can be moved to the comment marked with *1, below.

File: Assets/ZSSRichTextEditor.js [hunk 4]
```diff
@@ -273,49 +273,66 @@ ZSSEditor.getJoinedCaretArguments = function() {
...
+    if (! selection.rangeCount) { // if no selection available just return 0
+        this.caretInfo.y = y;
+        this.caretInfo.height = height;
+        return this.caretInfo;
+    }
+    
+    var range = selection.getRangeAt(0);
+    var needsToWorkAroundNewlineBug = (range.startOffset == 0 || range.getClientRects().length == 0);
+    
+    // PROBLEM: iOS seems to have problems getting the offset for some empty nodes and return
```
Comment (diegoreymendez) [inline Assets/ZSSRichTextEditor.js]: These comments can be removed now.

File: Assets/ZSSRichTextEditor.js [hunk 5]
```diff
@@ -273,49 +273,66 @@ ZSSEditor.getJoinedCaretArguments = function() {
...
+                //
+                var addsScrollOffset = document.body.getClientRects()[0].top < 0;
+                
+                if (addsScrollOffset) {
+                    y = document.body.scrollTop;
                 }
+                
+                y += rects[0].top;
+                height = rects[0].height;
             }
```
Comment (diegoreymendez) [inline Assets/ZSSRichTextEditor.js]: *1: add an `else` block here and add the code from the comment above.

File: Assets/ZSSRichTextEditor.js (hunk 1 above)
Comment (diegoreymendez) [inline Assets/ZSSRichTextEditor.js]: Nice check, good addition.

One note though, when comments are used to explain what the code is doing, it usually means that readability can be improved.

For example, instead of:

```javascript

ZSSEditor.getYCaretInfo = function() {
   var y = 0;
   var height = 0;
   var selection = window.getSelection();

   if (! selection.rangeCount) { // if no selection available just return 0
   // ...etc...
}
```

...use...

```javascript
/*
 * @returns {0, 0} if there is no selection.
 */
ZSSEditor.getYCaretInfo = function() {
   var y = 0;
   var height = 0;
   var selection = window.getSelection();

   var noSelection = !selection.rangeCount;

   if (noSelection) {
   // ...etc...
}
```

File: Assets/ZSSRichTextEditor.js [hunk 6]
```diff
@@ -273,49 +273,66 @@ ZSSEditor.getJoinedCaretArguments = function() {
...
+    var needsToWorkAroundNewlineBug = (range.startOffset == 0 || range.getClientRects().length == 0);
+    
+    // PROBLEM: iOS seems to have problems getting the offset for some empty nodes and return
+    // 0 (zero) as the selection range top offset.
+    //
+    // WORKAROUND: To fix this problem we just get the node's offset instead.
+    //
+    if (needsToWorkAroundNewlineBug) {
+        var closerParentNode = ZSSEditor.closerParentNode();
+        var closerDiv = ZSSEditor.closerParentNodeWithName('div');
```
Comment (diegoreymendez) [inline Assets/ZSSRichTextEditor.js]: I think this can be safely removed.

File: Assets/ZSSRichTextEditor.js [hunk 7]
```diff
@@ -273,49 +273,66 @@ ZSSEditor.getJoinedCaretArguments = function() {
...
+
+ZSSEditor.getYCaretInfo = function() {
+    var y = 0;
+    var height = 0;
+    var selection = window.getSelection();
+    
+    if (! selection.rangeCount) { // if no selection available just return 0
+        this.caretInfo.y = y;
+        this.caretInfo.height = height;
+        return this.caretInfo;
```
Comment (diegoreymendez) [inline Assets/ZSSRichTextEditor.js]: As we discussed in chat... use `{-999, -999}` for the time being, to signal there is no caret.

In the future we should return `null` and make sure that cascades back to the editor nicely.

Comment (diegoreymendez) [inline Assets/ZSSRichTextEditor.js]: Created a [new issue](https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/529) to improve this in version 4.9.

**Comment by diegoreymendez** [comment]
During testing I'm seeing problems with deleting the first word in a paragraph.  Also had problems setting the first word in a paragraph to bold or italic.

File: Assets/ZSSRichTextEditor.js [hunk 8]
```diff
@@ -273,49 +275,72 @@ ZSSEditor.getJoinedCaretArguments = function() {
...
+
 ZSSEditor.getYCaretInfo = function() {
-    var y = 0, height = 0;
-    var sel = window.getSelection();
-    if (sel.rangeCount) {
+    var y = 0;
+    var height = 0;
+    var selection = window.getSelection();
+    
+    if (! selection.rangeCount) { // if no selection available just return CaretPositionUnknow
```
Comment (diegoreymendez) [inline Assets/ZSSRichTextEditor.js]: When comments are used to explain what the code is doing, it usually means that readability can be improved to remove the comment.

For example, instead of:

```javascript

ZSSEditor.getYCaretInfo = function() {
   var y = 0;
   var height = 0;
   var selection = window.getSelection();

   if (! selection.rangeCount) { // if no selection available just return 0
   // ...etc...
}
```

...use...

```javascript
/*
 * @returns {0, 0} if there is no selection.
 */
ZSSEditor.getYCaretInfo = function() {
   var y = 0;
   var height = 0;
   var selection = window.getSelection();

   var noSelection = !selection.rangeCount;

   if (noSelection) {
   // ...etc...
}
```

File: Assets/ZSSRichTextEditor.js [hunk 9]
```diff
@@ -273,49 +275,72 @@ ZSSEditor.getJoinedCaretArguments = function() {
...
+        return this.caretInfo;
+    }
+    
+    var range = selection.getRangeAt(0);
+    var needsToWorkAroundNewlineBug = (range.startOffset == 0 || range.getClientRects().length == 0);
+    
+    // PROBLEM: iOS seems to have problems getting the offset for some empty nodes and return
+    // 0 (zero) as the selection range top offset.
+    //
+    // WORKAROUND: To fix this problem we just get the node's offset instead.
```
Comment (diegoreymendez) [inline Assets/ZSSRichTextEditor.js]: The last part of this comment should be changed to something like:

```objective-c:
// WORKAROUND: To fix this issue we use a different method to obtain the Y position instead.
```

File: Classes/WPEditorView.m [hunk 10]
```diff
@@ -1184,8 +1187,6 @@ - (void)insertLocalImage:(NSString*)url uniqueId:(NSString*)uniqueId
 {
     NSString *trigger = [NSString stringWithFormat:@"ZSSEditor.insertLocalImage(\"%@\", \"%@\");", uniqueId, url];
     [self.webView stringByEvaluatingJavaScriptFromString:trigger];
-    
-    [self workaroundiOS7FocusIssueAfterHidingBehindAnotherVC];
```
Comment (diegoreymendez) [inline Classes/WPEditorView.m]: Since the method being called is not used anywhere else anymore, you should remove it from the sources.

Comment (diegoreymendez) [inline Classes/WPEditorView.m]: Since the method being called is not used anywhere else anymore, you should remove it from the sources.

**Comment by diegoreymendez** [comment]
@SergioEstevao - Just some style comments above.  Please let me know when this is ready for a second :eyes: .

**Comment by diegoreymendez** [comment]
:shipit:
